# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = true

  config.vm.define "cent1"do |cent1|
    cent1.vm.hostname = "cent1"
    cent1.vm.network "private_network", ip:"192.168.33.11"
    cent1.vm.provider "virtualbox"do |v|
      v.name = "cent1"
      v.memory = 512
      v.cpus = 1
      v.linked_clone = true
      v.gui = false
    end

    cent1.vm.provision"shell",inline:<<-SHELL
     sudo yum -y updae
     sudo yum -y install net-tools vim
     sudo yum -y install epel-release
     sudo yum -y install ansible
     sudo yum -y install openssh-server openssh-clients openssh-askpass
    SHELL
 end

  config.vm.define "cent2"do |cent2|
    cent2.vm.hostname = "cent2"
    cent2.vm.network "private_network", ip:"192.168.33.12"
    cent2.vm.provider "virtualbox"do |v|
      v.name = "cent2"
      v.memory = 512
      v.cpus = 1
      v.linked_clone = true
      v.gui = false
    end

    cent2.vm.provision"shell",inline:<<-SHELL
     sudo yum -y updae
     sudo yum -y install net-tools vim
     sudo yum -y install epel-release
     sudo yum -y install openssh-server openssh-clients openssh-askpass
    SHELL
 end

  config.vm.define "cent3"do |cent3|
    cent3.vm.hostname = "cent3"
    cent3.vm.network "private_network", ip:"192.168.33.13"
    cent3.vm.provider "virtualbox"do |v|
      v.name = "cent3"
      v.memory = 512
      v.cpus = 1
      v.linked_clone = true
      v.gui = false
    end

    cent3.vm.provision"shell",inline:<<-SHELL
     sudo yum -y updae
     sudo yum -y install net-tools vim
     sudo yum -y install epel-release
     sudo yum -y install openssh-server openssh-clients openssh-askpass
    SHELL
 end
end
